<?php

namespace Config;

use CodeIgniter\Config\BaseConfig;

class DzConfig extends BaseConfig
{
    public $dzAssets = [

		/*
		|--------------------------------------------------------------------------
		| Application Name
		|--------------------------------------------------------------------------
		|
		| This value is the name of your application. This value is used when the
		| framework needs to place the application's name in a notification or
		| any other location as required by the application or its packages.
		|
		*/

		'name' => 'SAMF',
		

		'public' => [
			'favicon' => 'media/img/logo/favicon.ico',
			'fonts' => [
				'google' => [
					'families' => [
						'Poppins:300,400,500,600,700,800,900',
					]
				]
			],
			'global' => [
				'css' => [
					'public/assets/vendor/jquery-nice-select/css/nice-select.css',
					'public/assets/css/style.css',
					'public/assets2/css/styles.css',
					'public/assets/vendor/toastr/css/toastr.min.css',
					'public/assets/css/estilopessoal.css',
				],
				'js' => [
					'top'=>[
						'public/assets/vendor/global/global.min.js',
						'public/assets/vendor/jquery-nice-select/js/jquery.nice-select.min.js',	
						'public/assets/js/rotinas_v1.0.6.js',	
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'bottom'=>[
						'public/assets/js/custom.min.js',
						'public/assets/js/dlabnav-init.js',
					],
				],
			],
			'pagelevel' => [
				'css' => [
					'Work_index' => [
						'public/assets/vendor/owl-carousel/owl.carousel.css',
						'public/assets/vendor/nouislider/nouislider.min.css',
					],
					'Work_index_2' => [
						'public/assets/vendor/owl-carousel/owl.carousel.css',
						'public/assets/vendor/nouislider/nouislider.min.css',
					],
					'Work_kanban' => [
						'public/assets/vendor/owl-carousel/owl.carousel.css',
						'public/assets/vendor/nouislider/nouislider.min.css',
					],
					'Work_clients' => [
					],
					'Work_project_details' => [
						'public/assets/vendor/owl-carousel/owl.carousel.css',
						'public/assets/vendor/nouislider/nouislider.min.css',
					],
					'Work_message' => [
					],
					'Work_latest_activity' => [
					],
					'Work_app_profile' => [
						'public/assets/vendor/lightgallery/css/lightgallery.min.css',
					],
					'Work_post_details' => [
						'public/assets/vendor/lightgallery/css/lightgallery.min.css',
					],
					'Work_app_calender' => [
						'public/assets/vendor/fullcalendar/css/main.min.css',
					],
					'Work_chart_chartist' => [
						'public/assets/vendor/chartist/css/chartist.min.css',
					],
					'Work_chart_chartjs' => [
					],
					'Work_chart_flot' => [
					],
					'Work_chart_morris' => [
					],
					'Work_chart_peity' => [
					],
					'Work_chart_sparkline' => [
					],
					'Work_ecom_checkout' => [
					],
					'Work_ecom_customers' => [
					],
					'Work_logout' => [
						'public/assets/vendor/owl-carousel/owl.carousel.css',
						'public/assets/vendor/nouislider/nouislider.min.css',
					],
					'Work_ecom_invoice' => [
						'public/assets/vendor/bootstrap-select/dist/css/bootstrap-select.min.css',
					],
					'Work_ecom_product_detail' => [
						'public/assets/vendor/star-rating/star-rating-svg.css',
					],
					'Work_ecom_product_grid' => [
					],
					'Work_ecom_product_list' => [
						'public/assets/vendor/star-rating/star-rating-svg.css',
					],
					'Work_ecom_product_order' => [
					],
					'Work_email_compose' => [
						'public/assets/vendor/dropzone/dist/dropzone.css',
					],
					'Work_email_inbox' => [
					],
					'Work_email_read' => [
					],
					'Work_form_editor' => [
					],
					'Work_form_element' => [
					],
					'Work_form_pickers' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
					],
					'Work_form_validation' => [
					],
					'Work_form_wizard' => [
						'public/assets/vendor/jquery-smartwizard/dist/css/smart_wizard.min.css',
					],
					'Work_map_jqvmap' => [
						'public/assets/vendor/jqvmap/css/jqvmap.min.css',
					],
					'Work_table_bootstrap_basic' => [
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_Qrcodegerar' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
					],
					'Work_Qrcodeler' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
					],
					'Work_Qrcodeler' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
					],
					'Work_pesquisa' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
						'public/assets/vendor/select2/css/select2.min.css',
					],
					'Work_editar' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_atendimentoVS' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_BMKlabin' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_RDOPDF' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_atendimentoPL' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_atendimentoRDO' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
						'public/assets/vendor/select2/css/select2.min.css',
					],
					'Work_atendimentoRDOGestor' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_aprovagestoremail' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_aprovaclienteemail1' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_aprovaclienteemail2' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_atendimentoRDOCliente' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_rdo' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_Parametrizador' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_GeradorXML' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_UpdatesMovimentos' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_ItensRMFiscal' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_logObrasGeralController' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_SCAndaimes' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
						// 'public/assets/vendor/owl-carousel/owl.carousel.css',
						// 'public/assets/vendor/nouislider/nouislider.min.css',			
					],
					'Work_AA0140' => [
						'public/assets/vendor/owl-carousel/owl.carousel.css',
						'public/assets/vendor/nouislider/nouislider.min.css',		
					],
					'User_Usuarios' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_VSAndaimes' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_PRAndaimes' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_PLAndaimes' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_DocAnexos' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_table_datatable_basic' => [
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.css',
						'public/assets/vendor/clockpicker/css/bootstrap-clockpicker.min.css',
						'public/assets/vendor/jquery-asColorPicker/css/asColorPicker.min.css',
						'public/assets/vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css',
						'public/assets/vendor/pickadate/themes/default.css',
						'public/assets/vendor/pickadate/themes/default.date.css',
						'https://fonts.googleapis.com/icon?family=Material+Icons',
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_uc_lightgallery' => [
						'public/assets/vendor/lightgallery/css/lightgallery.min.css',
					],
					'Work_uc_nestable' => [
						'public/assets/vendor/nestable2/css/jquery.nestable.min.css',
					],
					'Work_uc_noui_slider' => [
						'public/assets/vendor/nouislider/nouislider.min.css',
					],
					'Work_uc_select2' => [
						'public/assets/vendor/select2/css/select2.min.css',
					],
					'Work_uc_sweetalert' => [
						'public/assets/vendor/sweetalert2/dist/sweetalert2.min.css',
					],
					'Work_uc_toastr' => [
						'public/assets/vendor/toastr/css/toastr.min.css',
					],
					'Work_ui_accordion' => [
					],
					'Work_ui_alert' => [
					],
					'Work_ui_badge' => [
					],
					'Work_ui_button' => [
					],
					'Work_ui_button_group' => [
					],
					'Work_ui_card' => [
					],
					'Work_ui_carousel' => [
					],
					'Work_ui_dropdown' => [
					],
					'Work_ui_grid' => [
					],
					'Work_ui_list_group' => [
					],
					'Work_ui_modal' => [
					],
					'Work_ui_pagination' => [
					],
					'Work_ui_popover' => [
					],
					'Work_ui_progressbar' => [
					],
					'Work_ui_tab' => [
					],
					'Work_ui_typography' => [
					],
					'Work_widget_basic' => [
						'public/assets/vendor/chartist/css/chartist.min.css',
						'public/assets/vendor/bootstrap-select/dist/css/bootstrap-select.min.css',
					],
					'Work_page_empty' => [
					],
				],
				'js' => [
					'Work_index' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/peity/jquery.peity.min.js',
						'public/assets/js/dashboard/dashboard-1.js',
						'public/assets/vendor/owl-carousel/owl.carousel.js',
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',	
					],
					'Work_logout' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						// 'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/peity/jquery.peity.min.js',
						'public/assets/js/dashboard/dashboard-1.js',
						'public/assets/vendor/owl-carousel/owl.carousel.js',
					],
					'Work_index_2' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						// 'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/peity/jquery.peity.min.js',
						'public/assets/js/dashboard/dashboard-1.js',
						'public/assets/vendor/owl-carousel/owl.carousel.js',
					],
					'Work_kanban' => [
						'public/assets/vendor/draggable/draggable.js',
					],
					'Work_clients' => [
					],
					'Work_project_details' => [
						'public/assets/vendor/draggable/draggable.js',
					],
					'Work_message' => [
					],
					'Work_latest_activity' => [
					],
					'Work_app_calender' => [
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/fullcalendar/js/main.min.js',
						'public/assets/js/plugins-init/fullcalendar-init.js',
					],
					'Work_app_profile' => [
						'public/assets/vendor/bootstrap-select/dist/js/bootstrap-select.min.js',	
						'public/assets/vendor/chart.js/Chart.bundle.min.js',	
						'public/assets/vendor/lightgallery/js/lightgallery-all.min.js',	
					],
					'Work_post_details' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',	
						'public/assets/vendor/lightgallery/js/lightgallery-all.min.js',	
					],
					'Work_chart_chartist' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/chartist/js/chartist.min.js',
						'public/assets/vendor/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js',
						'public/assets/js/plugins-init/chartist-init.js',
					],
					'Work_chart_chartjs' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/js/plugins-init/chartjs-init.js',
					],
					'Work_chart_flot' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/flot/jquery.flot.js',
						'public/assets/vendor/flot/jquery.flot.pie.js',
						'public/assets/vendor/flot/jquery.flot.resize.js',
						'public/assets/vendor/flot-spline/jquery.flot.spline.min.js',
						'public/assets/js/plugins-init/flot-init.js',
					],
					'Work_chart_morris' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/raphael/raphael.min.js',
						'public/assets/vendor/morris/morris.min.js',
						'public/assets/js/plugins-init/morris-init.js',
					],
					'Work_chart_peity' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/peity/jquery.peity.min.js',
						'public/assets/js/plugins-init/piety-init.js',
					],
					'Work_chart_sparkline' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/jquery-sparkline/jquery.sparkline.min.js',
						'public/assets/js/plugins-init/sparkline-init.js',
						'public/assets/vendor/svganimation/vivus.min.js',
						'public/assets/vendor/svganimation/svg.animation.js',
					],
					'Work_ecom_checkout' => [
					],
					'Work_ecom_customers' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/highlightjs/highlight.pack.min.js',
					],
					'Work_ecom_invoice' => [
					],
					'Work_ecom_product_detail' => [
						'public/assets/vendor/star-rating/jquery.star-rating-svg.js',
					],
					'Work_ecom_product_grid' => [
					],
					'Work_ecom_product_list' => [
						'public/assets/vendor/star-rating/jquery.star-rating-svg.js',
					],
					'Work_ecom_product_order' => [
					],
					'Work_email_compose' => [
						'public/assets/vendor/dropzone/dist/dropzone.js',
					],
					'Work_email_inbox' => [
					],
					'Work_email_read' => [
					],
					'Work_form_editor' => [
						'public/assets/vendor/ckeditor/ckeditor.js',
					],
					'Work_form_element' => [
					],
					'Work_form_pickers' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
					],
					'Work_form_validation' => [
					],
					'Work_form_wizard' => [
						'public/assets/vendor/jquery-steps/build/jquery.steps.min.js',
						'public/assets/vendor/jquery-validation/jquery.validate.min.js',
						'public/assets/js/plugins-init/jquery.validate-init.js',
						'public/assets/vendor/jquery-smartwizard/dist/js/jquery.smartWizard.js',
					],
					'Work_map_jqvmap' => [
						'public/assets/vendor/jqvmap/js/jquery.vmap.min.js',
						'public/assets/vendor/jqvmap/js/jquery.vmap.world.js',
						'public/assets/vendor/jqvmap/js/jquery.vmap.usa.js',
						'public/assets/js/plugins-init/jqvmap-init.js',
					],
					'Work_table_bootstrap_basic' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_OrcamentoAndaime' => [
					],
					'Work_Qrcodegerar' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
					],
					'Work_Qrcodeler' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
					],
					'Work_pesquisa' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
						'public/assets/vendor/select2/js/select2.full.min.js',
						'public/assets/js/plugins-init/select2-init.js',
					],
					'Work_editar' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_atendimentoVS' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_BMKlabin' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_RDOPDF' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_atendimentoPL' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_atendimentoRDO' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',	
						'public/assets/vendor/select2/js/select2.full.min.js',
						'public/assets/js/plugins-init/select2-init.js',
					],
					'Work_atendimentoRDOGestor' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_aprovagestoremail' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],					
					'Work_aprovaclienteemail1' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],		
					'Work_aprovaclienteemail2' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_atendimentoRDOCliente' => [
						'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js',
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_rdo' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',						
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',				
					],
					'Work_Parametrizador' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',						
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',	
					],
					'Work_GeradorXML' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',						
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',	
					],
					'Work_UpdatesMovimentos' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',						
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',	
					],
					'Work_ItensRMFiscal' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',						
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',	
					],
					'Work_logObrasGeralController' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',						
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',	
					],
					'Work_SCAndaimes' => [
						// 'public/assets/vendor/chart.js/Chart.bundle.min.js',
						// 'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						// 'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
						// 'public/assets/vendor/draggable/draggable.js',
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						// 'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',	
									
					],
					'Work_AA0140' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/peity/jquery.peity.min.js',
						'public/assets/js/dashboard/dashboard-1.js',
						'public/assets/vendor/owl-carousel/owl.carousel.js',									
					],
					'User_Usuarios' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',						
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',	
					],
					'Work_VSAndaimes' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_PRAndaimes' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_PLAndaimes' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',										
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',	
					],
					'Work_DocAnexos' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/moment/moment.min.js',
						'public/assets/vendor/bootstrap-daterangepicker/daterangepicker.js',
						'public/assets/vendor/clockpicker/js/bootstrap-clockpicker.min.js',
						'public/assets/vendor/jquery-asColor/jquery-asColor.min.js',
						'public/assets/vendor/jquery-asGradient/jquery-asGradient.min.js',
						'public/assets/vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js',
						'public/assets/vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js',
						'public/assets/vendor/pickadate/picker.js',
						'public/assets/vendor/pickadate/picker.time.js',
						'public/assets/vendor/pickadate/picker.date.js',
						'public/assets/js/plugins-init/bs-daterange-picker-init.js',
						'public/assets/js/plugins-init/clock-picker-init.js',
						'public/assets/js/plugins-init/jquery-asColorPicker.init.js',
						'public/assets/js/plugins-init/material-date-picker-init_V1.0.1.js',
						'public/assets/js/plugins-init/pickadate-init.js',
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_table_datatable_basic' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/datatables/js/jquery.dataTables.min.js',
						'public/assets/js/plugins-init/datatables.init.js',
					],
					'Work_uc_lightgallery' => [
						'public/assets/vendor/lightgallery/js/lightgallery-all.min.js',	
					],
					'Work_uc_nestable' => [
						'public/assets/vendor/nestable2/js/jquery.nestable.min.js',
						'public/assets/js/plugins-init/nestable-init.js',
					],
					'Work_uc_noui_slider' => [
						'public/assets/vendor/nouislider/nouislider.min.js',
						'public/assets/vendor/wnumb/wNumb.js',
						'public/assets/js/plugins-init/nouislider-init.js',
					],
					'Work_uc_select2' => [
						'public/assets/vendor/select2/js/select2.full.min.js',
						'public/assets/js/plugins-init/select2-init.js',
					],
					'Work_uc_sweetalert' => [
						'public/assets/vendor/sweetalert2/dist/sweetalert2.min.js',
						'public/assets/js/plugins-init/sweetalert.init.js',
					],
					'Work_uc_toastr' => [
						'public/assets/vendor/toastr/js/toastr.min.js',
						'public/assets/js/plugins-init/toastr-init.js',
					],
					'Work_ui_accordion' => [
					],
					'Work_ui_alert' => [
					],
					'Work_ui_badge' => [
					],
					'Work_ui_button' => [
					],
					'Work_ui_button_group' => [
					],
					'Work_ui_card' => [
					],
					'Work_ui_carousel' => [
					],
					'Work_ui_dropdown' => [
					],
					'Work_ui_grid' => [
					],
					'Work_ui_list_group' => [
					],
					'Work_ui_modal' => [
					],
					'Work_ui_pagination' => [
					],
					'Work_ui_popover' => [
					],
					'Work_ui_progressbar' => [
					],
					'Work_ui_tab' => [
					],
					'Work_ui_typography' => [
					],
					'Work_widget_basic' => [
						'public/assets/vendor/chart.js/Chart.bundle.min.js',
						'public/assets/vendor/apexchart/apexchart.js',
						'public/assets/vendor/chartist/js/chartist.min.js',
						'public/assets/vendor/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js',
						'public/assets/vendor/flot/jquery.flot.js',
						'public/assets/vendor/flot/jquery.flot.pie.js',
						'public/assets/vendor/flot/jquery.flot.resize.js',
						'public/assets/vendor/flot-spline/jquery.flot.spline.min.js',
						'public/assets/vendor/jquery-sparkline/jquery.sparkline.min.js',
						'public/assets/js/plugins-init/sparkline-init.js',
						'public/assets/vendor/peity/jquery.peity.min.js',
						'public/assets/js/plugins-init/piety-init.js',
						'public/assets/js/plugins-init/widgets-script-init.js',
					],
					'Work_page_empty' => [
					],	
				]
			],
		]
	];

}
